namespace LyricBuilder.Domain.Enums;

/// <summary>
/// Who wrote a section's text. Kept so generation can prefer human-written examples and never
/// learn from its own unreviewed output.
/// </summary>
public enum ContentOrigin
{
    Human = 0,
    AiGenerated = 1,

    /// <summary>Generated by the AI, then changed by a person.</summary>
    AiEdited = 2
}
